package main

import (
	"github.com/reiver/gogen-ld/driver"
)

func init() {

	driver := gendriver.SimpleDriver{
		NamePattern: "nullcomplainer.go",
		TextTemplate:
`// DO NOT EDIT
//
// MACHINE GENERATED BY THE FOLLOWING COMMAND
// gogen-ld --pkg={{.Pkg}} --type={{.Type}} --name={{.Name}}
package {{.Pkg}}

// THIS FILE IS GENERATED; DO NOT EDIT

type NullComplainer interface {
	error
	NullComplainer()
}

// THIS FILE IS GENERATED; DO NOT EDIT

type internalNullComplainer struct{}

// THIS FILE IS GENERATED; DO NOT EDIT

func (receiver internalNullComplainer) Error() string {
	return "Null"
}

// THIS FILE IS GENERATED; DO NOT EDIT

func (internalNullComplainer) NullComplainer() {
	// Nothing here.
}
`}

	registry := gendriver.Registry
	if nil == registry {
		panic(errNilRegistry)
	}

	if err := registry.Register(driver.NamePattern, driver); nil != err {
		panic(err)
	}
}
