package main

import (
	"github.com/reiver/gogen-ld/driver"
)

func init() {

	driver := gendriver.SimpleDriver{
		NamePattern: "{{.Name}}_some.go",
		TextTemplate:
`// DO NOT EDIT
//
// MACHINE GENERATED BY THE FOLLOWING COMMAND
// gogen-ld --pkg={{.Pkg}} --type={{.Type}} --name={{.Name}}
package {{.Pkg}}

// THIS FILE IS GENERATED; DO NOT EDIT

{{range .Imports}}
import "{{.}}"
{{end}}

// THIS FILE IS GENERATED; DO NOT EDIT

// {{.Name}}Some returns an {{.Name}} with a value.
//
// For example:
//
//	var x {{.Pkg}}.{{.Name}} = {{.Pkg}}.{{.Name}}Some(value)
func {{.Name}}Some(v {{.Type}}) {{.Name}} {
	return {{.Name}} {
		value: v,
		loaded: true,
	}
}
`}

	registry := gendriver.Registry
	if nil == registry {
		panic(errNilRegistry)
	}

	if err := registry.Register(driver.NamePattern, driver); nil != err {
		panic(err)
	}
}
