package main

import (
	"github.com/reiver/gogen-ld/driver"
)

func init() {

	driver := gendriver.SimpleDriver{
		NamePattern: "{{.Name}}_none_null.go",
		TextTemplate:
`// DO NOT EDIT
//
// MACHINE GENERATED BY THE FOLLOWING COMMAND
// gogen-ld --pkg={{.Pkg}} --type={{.Type}} --name={{.Name}}
package {{.Pkg}}

// THIS FILE IS GENERATED; DO NOT EDIT

type {{.Name}}NoneNull struct{}

// THIS FILE IS GENERATED; DO NOT EDIT

func ({{.Name}}NoneNull) String() string {
	return "<{{.Name}}Null>"
}

// THIS FILE IS GENERATED; DO NOT EDIT

// Nullable{{.Name}}Matcher makes {{.Name}}NoneNull fit the Nullable{{.Name}}Matcher interface.
func ({{.Name}}NoneNull) Nullable{{.Name}}Matcher() {
	// Nothing here.
}
`}

	registry := gendriver.Registry
	if nil == registry {
		panic(errNilRegistry)
	}

	if err := registry.Register(driver.NamePattern, driver); nil != err {
		panic(err)
	}
}
