package main

import (
	"github.com/reiver/gogen-ld/driver"
)

func init() {

	driver := gendriver.SimpleDriver{
		NamePattern: "nullable_{{.Name}}_notloaded.go",
		TextTemplate:
`// DO NOT EDIT
//
// MACHINE GENERATED BY THE FOLLOWING COMMAND
// gogen-ld --pkg={{.Pkg}} --type={{.Type}} --name={{.Name}}
package {{.Pkg}}

// THIS FILE IS GENERATED; DO NOT EDIT

// Nullable{{.Name}}NotLoaded returns a Nullable{{.Name}} which does not have a value;
// and in particular the "not loaded" type of a lack of a value.
//
// For example:
//
//	var x {{.Pkg}}.Nullable{{.Name}} = {{.Pkg}}.Nullable{{.Name}}NotLoaded()
func Nullable{{.Name}}NotLoaded() Nullable{{.Name}} {
	return Nullable{{.Name}}{}
}
`}

	registry := gendriver.Registry
	if nil == registry {
		panic(errNilRegistry)
	}

	if err := registry.Register(driver.NamePattern, driver); nil != err {
		panic(err)
	}
}
