package main

import (
	"github.com/reiver/gogen-ld/driver"
)

func init() {

	driver := gendriver.SimpleDriver{
		NamePattern: "nullable_{{.Name}}_null.go",
		TextTemplate:
`// DO NOT EDIT
//
// MACHINE GENERATED BY THE FOLLOWING COMMAND
// gogen-ld --pkg={{.Pkg}} --type={{.Type}} --name={{.Name}}
package {{.Pkg}}

// THIS FILE IS GENERATED; DO NOT EDIT

// Nullable{{.Name}}Null returns a Nullable{{.Name}} which does not have a value;
// and in particular the "null" type of a lack of a value.
//
// For example:
//
//	var x ld.Nullable{{.Name}} = ld.Nullable{{.Name}}Null()
func Nullable{{.Name}}Null() Nullable{{.Name}} {
	return Nullable{{.Name}}{
		loaded: true,
		null: true,
	}
}
`}

	registry := gendriver.Registry
	if nil == registry {
		panic(errNilRegistry)
	}

	if err := registry.Register(driver.NamePattern, driver); nil != err {
		panic(err)
	}
}
